backend:
  name: github
  repo: SMagic-L/blog-smagic-top # Path to your Github repository
  # optional, defaults to master
  branch: main
  use_graphql: true
  squash_merges: true
# This line should *not* be indented

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow


collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
