name: Deploy Gatsby Blog to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Build the Gatsby site
    - name: Build the site
      run: npm run build

    # Deploy to GitHub Pages branch
    - name: Deploy to GitHub Pages
      run: |
        # Ensure you are in the right directory
        cd public
        # Initialize a new git repository
        git init
        # Configure git
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # Add all files and commit
        git add .
        git commit -m "Deploy Gatsby site"
        # Push to the pages branch
        git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" main:pages
